(IFL-954) Send page updates.
iron-fish/node-app pull request #282
Opened 2023-05-19 12:40 UTC by azhurauski-sc

2023-05-19 12:52 UTC, ndemidovich-sc approved these changes

2023-05-23 14:29 UTC, skylarrichard123 requested changes
@dgca tasks from https://linear.app/if-labs/issue/IFL-966/fix-line-break have not been implemented here.

2023-05-25 19:10 UTC, dgca commented on src/routes/Send/Send.tsx
> +                  setAmount('0.')
If the user starts with an empty input and plops a `.`, we'll prepend a 0 for formatting purposes.

2023-05-25 20:24 UTC, jowparks approved these changes

2023-05-26 17:24 UTC, merged