feat(ifl-1047): reset node and confirm modal
iron-fish/node-app pull request #302
Opened 2023-06-02 18:01 UTC by jowparks

## Summary:
- Adds a `ConfirmModal` component (will be reused for account deletion).
- Uses that component for confirming node reset.
- Updates `IronFishManager` to have `resetNode` method callable from frontend.
- onConfirm will reset the node and restart the app

https://github.com/iron-fish/node-app/assets/26990067/02034166-59b1-4eba-a38f-6f29473c8589

2023-06-04 19:02 UTC, skylarrichard123 requested changes
<img width="588" alt="Screen Shot 2023-06-04 at 4 00 53 PM" src="https://github.com/iron-fish/node-app/assets/75860817/ce28dfef-2c7a-44e5-80cf-21ea63e91599">

I'd be weary of creating new button styling as it'll create inconsistencies within the app. 

Checkout an account's settings and see the delete text link as an example of how we've implemented ui patterns in this vein. @dgca not sure if you want to handle the implementation or not?

2023-06-05 02:40 UTC, jowparks commented
> <img alt="Screen Shot 2023-06-04 at 4 00 53 PM" width="588" src="https://user-images.githubusercontent.com/75860817/243201526-ce28dfef-2c7a-44e5-80cf-21ea63e91599.png">
> I'd be weary of creating new button styling as it'll create inconsistencies within the app.
> 
> Checkout an account's settings and see the delete text link as an example of how we've implemented ui patterns in this vein. @dgca not sure if you want to handle the implementation or not?

Not sure what you mean, I made the background invisible before hover like in the design. I can remove the background on hover as well if that is what you want.

2023-06-05 02:43 UTC, jowparks commented
> <img alt="Screen Shot 2023-06-04 at 4 00 53 PM" width="588" src="https://user-images.githubusercontent.com/75860817/243201526-ce28dfef-2c7a-44e5-80cf-21ea63e91599.png">
> I'd be weary of creating new button styling as it'll create inconsistencies within the app.
> 
> Checkout an account's settings and see the delete text link as an example of how we've implemented ui patterns in this vein. @dgca not sure if you want to handle the implementation or not?

I see what you mean, I will just make it a link rather than a button. Not sure what you mean by linking @dgca in here, hopefully he can sus it out.

2023-06-05 13:28 UTC, skylarrichard123 commented
@jowparks sounds good. Was tagging dan because he's one of the ui kit owners and I wasn't sure if you had access to the existing design patterns from it, but the feedback is probably straight forward enough.

2023-06-05 18:27 UTC, dgca approved these changes

2023-06-07 17:05 UTC, skylarrichard123 commented
<img width="525" alt="Screen Shot 2023-06-07 at 2 05 26 PM" src="https://github.com/iron-fish/node-app/assets/75860817/a73c4e90-9fb8-4e87-8e0d-769c80378a53">

2023-06-07 17:13 UTC, jowparks commented
> <img alt="Screen Shot 2023-06-07 at 2 05 26 PM" width="525" src="https://user-images.githubusercontent.com/75860817/244144957-a73c4e90-9fb8-4e87-8e0d-769c80378a53.png">

Ya I fixed this in the updated version

2023-06-07 17:30 UTC, skylarrichard123 approved these changes

2023-06-07 18:06 UTC, merged