feat(ifl-1038): change 0.0 iron to 0
iron-fish/node-app pull request #327
Opened 2023-06-13 17:53 UTC by jowparks

<img width="1342" alt="Screenshot 2023-06-13 at 10 51 44 AM" src="https://github.com/iron-fish/node-app/assets/26990067/34304296-9323-4c0b-b43b-01d9493c2428">
<img width="1357" alt="Screenshot 2023-06-13 at 10 51 32 AM" src="https://github.com/iron-fish/node-app/assets/26990067/68721b47-83c3-4937-a9d4-6d229f1fb03b">

2023-06-13 18:01 UTC, skylarrichard123 requested changes
The 0 $IRON in the send card is now off balance

2023-06-13 20:05 UTC, jowparks commented
> The 0 $IRON in the send card is now off balance

Good catch, fixed

2023-06-14 12:25 UTC, skylarrichard123 approved these changes

2023-06-14 17:14 UTC, rohanjadvani approved these changes

2023-06-14 19:58 UTC, merged